version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t lemon-mart:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar lemon-mart:$CIRCLE_BRANCH
      - save_cache:
          key: built-image-{{ .BuildNum }}
          paths:
            - docker-cache
      - store_artifacts:
          path: docker-cache/built-image.tar
          destination: built-image.tar

  deploy:
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - restore_cache:
        keys:
          - built-image-{{ .BuildNum }}
          - built-image
      - setup_remote_docker
      - run:
          name: Sign into AWS ecr
          command: $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
          name: Push it to ECR
          command: |
            docker load < docker-cache/built-image.tar
            docker tag my_app:$CIRCLE_BRANCH $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/lemon-mart:$CIRCLE_BRANCH
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/lemon-mart:$CIRCLE_BRANCH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
# Deployment Integrations https://circleci.com/docs/2.0/deployment-integrations
# For Docker Hub deploy see https://circleci.com/docs/2.0/building-docker-images/
# For AWS ECS deploy see https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
# For Heroku see https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-image-s
# For cache optimization read https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
